mail.smtp.host=sandbox.smtp.mailtrap.io
mail.smtp.port=2525
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.username=d682414db25e6e
mail.smtp.password=********
# Please replace the username and password with your real Mailtrap or Gmail credentials.
mail.from=noreply@carnivalrental.com
